name: springboot

on:
  push:
    branches:
      - master  # push되면 실행될 브랜치를 선택합니다.
  workflow_dispatch: # 수동 실행

jobs:
  build:
    runs-on: ubuntu-latest # 수행되는 os 환경
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # github에서 프로젝트를 다운받음

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1.4.3 # os에 java 설치
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew #gradlewrapper에 실행권한 추가
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build # gradlew로 빌도 (test & jar 파일 생성을 수행)
        shell: bash